version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Disable all pull requests for GitHub Actions dependencies
    open-pull-requests-limit: 0

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/18.04/default"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "ubuntu"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]

  - package-ecosystem: "docker"
    directory: "/20.04/default"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "ubuntu"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]

  - package-ecosystem: "docker"
    directory: "/22.04/default"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "ubuntu"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
